runtime: python312
instance_class: F4
automatic_scaling:
  target_cpu_utilization: 0.90
  max_instances: 1
entrypoint: gunicorn -b :$PORT app:server
env_variables:
  BUCKET_NAME: 'cs163-website.appspot.com'
